#!/usr/bin/env bash

docker build . -t cjtaylor/jenkins-job-builder > /dev/null 2>&1

if hash cygpath 2>/dev/null; then 
    CONFIG_PATH=$(cygpath -aw $(pwd)/jenkins_jobs.ini)
else 
    CONFIG_PATH=$PROJECT_ROOT/jenkins_jobs.ini
fi 

docker run --interactive \
    --tty \
    --rm \
    --name jjb \
    --volume "$CONFIG_PATH":/etc/jenkins_jobs/jenkins_jobs.ini \
    cjtaylor/jenkins-job-builder \
    jenkins-jobs --version